# Generated by Django 5.1 on 2024-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofee',
            name='image',
            field=models.ImageField(upload_to='coffee_images/'),
        ),
    ]
