# Generated by Django 5.1 on 2024-11-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0002_alter_cofee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email_id', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
