# Generated by Django 5.1 on 2024-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofee',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
