# Generated by Django 5.1 on 2024-11-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0004_alter_cofee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email_id',
            field=models.EmailField(max_length=100),
        ),
    ]
