# Generated by Django 5.1 on 2024-11-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0006_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofee',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
