# Generated by Django 5.1 on 2024-12-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0007_alter_cofee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofee',
            name='location',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
